export const ADD_FEATURE_LAYER = 'ADD_FEATURE_LAYER';
export const ADD_FEATURE_LAYER_SUCCESSFUL = 'ADD_FEATURE_LAYER_SUCCESSFUL';
export const ADD_FEATURE_LAYER_FAILED = 'ADD_FEATURE_LAYER_FAILED';
export const QUERY_WAZE_BY_GEOMETRY = 'QUERY_WAZE_BY_GEOMETRY';
export const QUERY_WAZE_BY_GEOMETRY_SUCCESSFUL = 'QUERY_WAZE_BY_GEOMETRY_SUCCESSFUL';
export const QUERY_WAZE_BY_GEOMETRY_FAILED = 'QUERY_WAZE_BY_GEOMETRY_FAILED';